### ISSUE TITLE
Sqlite error 14 with a custom sqlite

### ISSUE THREAD

**Issue by hdlj** [swiftlyfalling/SQLiteLib#7] opened 2016-07-08 10:11 UTC
Hello, 

Thanks for this project!

I am trying to use sqlite with FTS5 module.

Here is my configuration:

CUSTOM_SQLLIBRARY_CFLAGS = -DSQLITE_ENABLE_FTS5

When I try this: 
``` 
sqlite3_open_v2
```

I get an error 14 (CONNOT_OPEN) with a new database

I have followed the step you recommend without success, do you have any idea of what I've missed?

Thanks in advance for your answer!

**Comment by groue** [comment] 2016-07-08 11:46
This is a cross-posted issue (source: https://github.com/groue/GRDB.swift/issues/80)

**Comment by swiftlyfalling** [comment] 2016-07-08 18:57
Hmmm.

I took the latest version of GRDB, and modified the GRDBDemoiOS project to use GRDBCustomSQLite built with SQLITE_ENABLE_FTS5.

The app builds and executes without issues. It creates, reads, and modifies the database without issues.

So as of now I cannot reproduce the error you are seeing.

Can you provide a sample project that exhibits this issue?

**Comment by hdlj** [comment] 2016-07-11 11:25
Hello swiftyfalling, 

Thanks for your answer. After your message I try to compare the code and I've found something which causes the crash. It is in the database path: 

This one works:
```
        let documentsPath = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true).first! as NSString
        let databasePath = documentsPath.stringByAppendingPathComponent("db.sqlite")
        let db = DatabaseQueue(path: databasePath) // "/path/to/database/db.sqlite"
```

This one issue error 14

```
        let documentsURL = NSURL(fileURLWithPath: NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true).first!)
        let databasePath = documentsURL.URLByAppendingPathComponent("db.sqlite").absoluteString 
       let db = DatabaseQueue(path: databasePath) // "file:///path/to/database/db.sqlite"   
```

However the second approach works with the normal sqlite. I don't know why the custom sqlite have a different behaviour for this.

**Comment by groue** [comment] 2016-07-12 09:58
The correct way is the path. Either by building paths as strings, either by taking the `path` property of a NSURL (not absoluteString).

There is no issue with SQLite or GRDB, maybe a behavior change in SQLite that has hit you. Anyway the DatabaseQueue initializer takes a *path*, and giving it a "file://" URL, which is *not* a path, is begging for troubles.

Conclusion : change your code, so that it gives paths to methods that ask for paths.

**Comment by swiftlyfalling** [comment] 2016-08-15 18:11
@hdlj: Since it looks like your issue is resolved, I'm closing this issue.

**Closed by swiftlyfalling** 2016-08-15 18:11 UTC
